### ISSUE TITLE
Node processes being orphaned and potentially duplicated when changing revisions

### ISSUE THREAD

**Issue by andressaroberts** [clutch-creator/clutch#1]
What I was doing up to this point was selecting different revisions to try and find a working version of a project that has crashed. I noticed that the app gets really slow and takes some time changing between revisions. I had probably changed between a 5 or 6 before my computer started freezing up. Not sure if this is a helpful start point or not
Even now after reopening the app after doing the pkill command I have fp austin up as my only open project and I have several node processes running. I should not have anything else running on my computer at the moment that would be adding to this list so I am not sure what is happening.

https://github.com/clutch-creator/clutch/assets/22499533/47505ed8-5e44-4f58-8901-90e768ecac33

**Comment by magalhas** [comment]
It looks like this is related to vercel/next.js#45508. Apparently from next.js 13.3 forward orphaned jest processes are being leftover. This happens everytime we switch revisions. Downgrading to 13.2 could be a temporary fix but I'm not sure about the side-effects of doing the downgrade as of now.

**Comment by magalhas** [comment]
Apparently a fix has been pushed into next.js repository. Waiting for a RC to test it out.

**Comment by magalhas** [comment]
After testing with `next.js@13.4.20-canary.11` the bug appear to have been fixed.

**Comment by magalhas** [comment]
`next.js@13.5.1` got released and I don't seem to be able to reproduce the problem anymore.

**Comment by andressaroberts** [comment]
Tested on Canary
