### ISSUE TITLE
It should be possible to scroll on a page even without being in interaction mode

### ISSUE THREAD

**Issue by andressaroberts** [clutch-creator/clutch#10]
### How to reproduce

1. Be in the Pages session
2. Have enough items that require scrolling
3. Try to scroll the page

### Describe the bug

Currently it is only possible to scroll while on a page if the interaction mode is activated.

### Expected behavior

Scrolling needs to work both in interaction (play) and selection mode.

### Operating System

macOS 13.5

**Comment by joseBasso** [comment]
Moved this to our board because I needed a small task and didn't want to take one of the "good first issue"s

**Comment by andressaroberts** [comment]
Sometimes, we have some friction (it does not scroll immediately) but generally it is working.

Gracias, @joseBasso 🥳

https://github.com/clutch-creator/clutch/assets/22499533/2237db27-d1bc-4c01-ba00-299b3c9934d6

**Comment by joseBasso** [comment]
Couldn't replicate locally so I incremented the timeout. We eventually need to come up with a more robust solution that doesn't let other evens flow through but hopefully this helps for now

**Comment by andressaroberts** [comment]
@joseBasso I didn't feel much difference 🥲

**Comment by joseBasso** [comment]
It looks like a bug from chromium 😢 https://bugs.chromium.org/p/chromium/issues/detail?id=1476702
We probably can't afford to wait for a fix so let's try to find a workaround
