### ISSUE TITLE
Default Clutch Favicon

### ISSUE THREAD

**Issue by andressaroberts** [clutch-creator/clutch#12]
### How to reproduce

Create a new project
It won't have a Clutch favicon on localhost when you open in a new window

### Describe the bug

We should ship a default Clutch Favicon with all projects and templates. Reason being, if you don't have a favicon, it defaults to the last favicon that was used. On localost, the last favicon I had was of a rabbit, now my clutch projects on localhost show rabbits instead of a fancy clutch logo. I believe shipping our own clutch logo as a default favicon that the user can replace is better than not shipping one at all. Next projects ship with a default facion as well. So do WordPress sites.

### Operating System

Chrome 112 (macOS Catalina)

**Comment by andressaroberts** [comment]
@delila94 I could not reproduce the error of removing an icon and viewing the removed icon on localhost or after the published project.
I added the icon to the content/layout section and made publications, and never once did the icon remain after being removed.

**Comment by delila94** [comment]
Changes done in Minimal Template.. we ship Clutch favicon.ico in media manager, which is automatically set as favicon if user didn't specified icon in metadata

**Comment by andressaroberts** [comment]
LGTM 🎉
