### ISSUE TITLE
SVG showing up broken in media manager, but works

### ISSUE THREAD

**Issue by andressaroberts** [clutch-creator/clutch#16]
### How to reproduce

In the media manager, github.svg appears broke, but it does work.

![image](https://github.com/clutch-creator/clutch/assets/22499533/3aa7193b-91fc-4a2e-894c-4c84ecbeded4)

### Describe the bug

SVG showing up broken in media manager, but works

### Operating System

Chrome 112 (macOS Catalina)

**Comment by delila94** [comment]
@andressaroberts I can't reproduce this issue.. can you please take a look, and give more details or specific svg that made a problem

![Image](https://github.com/clutch-creator/clutch/assets/64300902/65871532-2f41-4429-8133-dd39ec4b9798)

**Comment by andressaroberts** [comment]
I couldn't reproduce it either. 
@MatthewHager / @daprieu Can you add us to the project or provide a copy so we can debug?
