### ISSUE TITLE
Editing text, get 500 error

### ISSUE THREAD

**Issue by andressaroberts** [clutch-creator/clutch#17]
### How to reproduce

Edit a lot of text.

### Describe the bug

Sometimes I'll be editing text, and I'll get hit with a 500 error. 
If I close the app and reopen, things go back to normal.

### Operating System

Chrome 112 (macOS Catalina)

**Comment by andressaroberts** [comment]
@MatthewHager I could not reproduce it so I need more information:

- Did this happen once or multiple times?
- Does the problem happen when editing the text primitive or some other type of component?

**Comment by magalhas** [comment]
Closing this because it was auto-archived in the project (still lacking the automation to close the issue).
