### ISSUE TITLE
Clutch version in tool does not match the version that is downloaded

### ISSUE THREAD

**Issue by andressaroberts** [clutch-creator/clutch#18]
### How to reproduce

1. open clutch
2. open project
3. open clutch menu
4. look at version number
5. ...profit?

### Describe the bug

Clutch version in tool does not match the version that is downloaded.
If you are in a project and open the Clutch menu the version number is stuck reporting that it is version 1.201.x while the actual version displayed in the clutch info is the correct version.

![image](https://github.com/clutch-creator/clutch/assets/22499533/ee44ca4a-aa18-46a3-9fbe-ca4ee336d7f4)

### Operating System

Chrome 112 (macOS Catalina)

**Comment by andressaroberts** [comment]
In the Menu, add the interface and desktop versions as they may have different numbers.
![image](https://github.com/clutch-creator/clutch/assets/22499533/82cf9f23-c89c-4a3b-9879-a356cc03c779)


The context-menu version can be removed.

![image](https://github.com/clutch-creator/clutch/assets/22499533/aed8cb7c-34ff-4980-8228-ccfc42414890)

**Comment by magalhas** [comment]
The expected behaviour is to show both versions on the about window (if possible). The version from the context menu can be removed as well.
