### ISSUE TITLE
When duplicating a free floating instance, the duplicate instance stays in the same position

### ISSUE THREAD

**Issue by diogomartino** [clutch-creator/clutch#20]
### How to reproduce

1. Create a free floating instance
2. Duplicate it
-------
Extra scenario:
- Deleting everything from a space and trying to add a primitive again -> inconsistent behaviour

### Describe the bug

The duplicated instance stays on top of the other one.

### Expected behavior

The new instance should be on the side of the original one, aligned.

### Operating System

Ubuntu 22.04

https://github.com/clutch-creator/clutch/assets/16502356/4287e0a3-a092-42d6-9877-bbae72719060

**Comment by andressaroberts** [comment]
🥳 


https://github.com/clutch-creator/clutch/assets/22499533/c9e85a92-8fa8-46f7-a97e-d82a639b6489



https://github.com/clutch-creator/clutch/assets/22499533/f254fc97-4744-4a92-a1df-18e8dcfd480b
