### ISSUE TITLE
LocalHost Fetch bug

### ISSUE THREAD

**Issue by AaronLehnen** [clutch-creator/clutch#24]
### How to reproduce

Try to fetch a localhost URL data.

### Describe the bug

Crashes canvas when trying to fetch data from localhost

### Expected behavior

To fetch localhost data

### Operating System

MacOS 13.4.1

### Clutch Version

Desktop: 1.201.0 

### Other

Interface: staging-3c59afc137bfedb62269323b4d100555c82363c7

**Comment by daprieu** [comment]
@andressaroberts We are going to archive this ticket for now.
