### ISSUE TITLE
Replace AWS docker registry with a self hosted instance inside the cluster powered by S3

### ISSUE THREAD

**Issue by magalhas** [clutch-creator/clutch#28]
- [x] Replace the service
- [x] Migrate most recent images
- [x] Cron job that cleans up old images (a retention policy needs to be defined)

**Comment by tmota900** [comment]
![Screenshot 2023-10-26 at 12 38 16](https://github.com/clutch-creator/clutch/assets/48350728/150fd3b4-d71b-4b5f-b869-7aa488a46d10)
> Build Process

![image](https://github.com/clutch-creator/clutch/assets/48350728/f714d44c-9fec-4642-88d4-3c3291c80431)
> Deploy Process

![image](https://github.com/clutch-creator/clutch/assets/48350728/75426c9f-b63d-46e1-a3b8-6497d469e75e)
> Deployed Pods
