### ISSUE TITLE
Theming not applied to components exported on the marketplace

### ISSUE THREAD

**Issue by andressaroberts** [clutch-creator/clutch#43]
### How to reproduce

1. Create a new project
2. Create a new collection in the theme variables
3. Create a new component
4. In styles, use the variables created
5. Export the component to the marketplace
6. Install your package in another project and notice that the styles are not applied

https://jam.dev/c/e1124258-4cc4-4732-868f-9db3f0b3fbdf

### Describe the bug

Project sample in Canary: https://app-staging.clutch.io/project/65771aa9169de1f82de8580d (Test Component)

### Expected behavior

The styles should be applied.

### Operating System

macOS 14.1.1

### Clutch Version

Desktop: 1.207.1-alpha.0ce7298de1 | Interface: 72298d1

**Comment by daprieu** [comment]
We need to PJ this, and the introduction of a default set of scales and semantic tokens may alleviate this issue
